version: "3.8"

x-common-variables: &common-variables
  MYSQL_DATABASE: fundraisers
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - "9906:3306"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_DB_CONN_STRING=mongodb://AzureDiamond:hunter2@mongodb

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
